import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import { Input } from "@nextui-org/input";
import { Toaster } from "react-hot-toast";

import { NextUIProvider } from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider>
          <header className="h-[133px] border-b border-black px-[130px]">
            <div className="pt-[20px] flex justify-between">
              <Image src={"/logo.png"} width={150} height={45} alt="logo" />
              <div className="h-[26px] text-[16px]">EN | FR | ES</div>
            </div>
            <div className="mt-[17px] mb-[5px] flex justify-between">
              <div className="w-[437px] h-[46px] flex justify-between items-center">
                <Link href={"/"}>
                  <h1 className="text-[14.4px]">Home</h1>
                </Link>
                <h1 className="text-[14.4px]">Partner Portal</h1>
                <h1 className="text-[14.4px]">PR Forum</h1>
                <h1 className="text-[14.4px]">Social Media</h1>
              </div>
              <Input
                placeholder="search"
                color="primary"
                classNames={{
                  base: "w-[180px]",
                  inputWrapper:
                    "h-[46px] bg-[#2E4DF9] rounded-[3px] pl-[10px] pr-[0px] data-[hover=true]:bg-[#2E4DF9] group-data-[focus=true]:bg-[#2E4DF9]",
                  input: "text-[14.29px] text-white placeholder:text-white",
                }}
                endContent={
                  <Image
                    src={"/search.svg"}
                    width={33}
                    height={33}
                    alt="search"
                  />
                }
              />
            </div>
          </header>

          <main>{children}</main>

          <Toaster position="bottom-center" />

          <footer className="relative h-[450px] border-t border-[#E8E8E8] mt-[60px]">
            <div className="px-[130px] absolute w-full bottom-0">
              <Image
                className="w-full"
                src={"/footer.png"}
                width={1180}
                height={450}
                alt="footer"
              />
            </div>
            <div className="absolute top-0 px-[130px] w-full">
              <div className="w-full flex justify-between mt-[46px]">
                <Image src={"/logo2.png"} width={150} height={50} alt="logo2" />
                <div className="w-[400px] h-[41px] flex justify-between items-center">
                  <h1 className="text-[15px]">Home</h1>
                  <h1 className="text-[15px]">Partner Portal</h1>
                  <h1 className="text-[15px]">PR Forum</h1>
                </div>
              </div>
              <div className="flex gap-[10px] mt-[20px]">
                <Image
                  src={"/facebook.png"}
                  width={26}
                  height={26}
                  alt="facebook"
                />
                <Image
                  src={"/twitter.png"}
                  width={26}
                  height={26}
                  alt="twitter"
                />
                <Image
                  src={"/linkedin.png"}
                  width={26}
                  height={26}
                  alt="linkedin"
                />
                <Image
                  src={"/instagram.png"}
                  width={26}
                  height={26}
                  alt="instagram"
                />
              </div>
              <div className="mt-[18px]">
                © 2024 The Global Fund to Fight AIDS, Tuberculosis and Malaria
              </div>
            </div>
          </footer>
        </NextUIProvider>
      </body>
    </html>
  );
}
